### PR TITLE
Make primary and primary-2 a bit lighter.

### PR DESCRIPTION
**Pull request by thorwebdev**
@leerob in the sketches on Slack the background was a bit more `#2d3748` which I really liked. Wdyt of this?

### CODE REVIEW

**Comment by leerob** [comment]
Sorry, I needed to send the updated designs. I'll drop them in Slack. We wanted to keep the black 👍🏼

**Comment by thorwebdev** [comment]
Ah, that's a bummer, I really prefer the dark blue, but fair enough 👍

**Comment by leerob** [comment]
Reasoning: We're trying to keep parity with colors somewhat across the starters so they look and feel similar.

**Comment by thorwebdev** [comment]
Ack 👍

**Pull request closed without merging**
